// Custom Worker entry: serves the Next.js app (OpenNext) and runs the daily reminder cron.
// @ts-ignore generated by `opennextjs-cloudflare build`
import handler from "./.open-next/worker.js";

type Env = Record<string, string | undefined>;

export default {
  fetch: handler.fetch,

  async scheduled(_event: unknown, env: Env, ctx: { waitUntil(p: Promise<unknown>): void }) {
    const base = env.NEXT_PUBLIC_SITE_URL ?? "https://dealdesk.craftloop.ca";
    const req = new Request(`${base}/api/cron/reminders`, { headers: { authorization: `Bearer ${env.CRON_SECRET ?? ""}` } });
    ctx.waitUntil(handler.fetch(req, env, ctx));
  },
};
